### ISSUE TITLE
Wireguard client not running in lbr20

### ISSUE THREAD

**Issue by jurek224466** [SVoxel/ORBI-LBR20#2]
I am having trouble launching the Wireguard client. After adding the configuration file and following the steps, it does not establish VPN connection. I don't know how to check VPN client logs. The configuration file was checked on the computer and it works correctly. The latest LBR20-V9.2.5.2.28SF-HW firmware is loaded.

**Comment by SVoxel** [comment]
I've tested WG client with my LBR20: it works.

Important note: you should NOT use the WireGuard config you got from your VPN provider 'as is'. But create your own specific config according to QuickStart.txt instructions. Example:
`
EndPoint="wireguard.5july.net"
LocalIP="10.0.xxx.xxx/24"
PrivateKey="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX="
PublicKey="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX="
Port="48574"
`
NOTE: no spaces before/after "=" symbol in example above.
NOTE: the name of the file wireguard.conf is lowercase.
NOTE: optional line could be added if your providers requires that:

PresharedKey="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX="

Voxel.

**Comment by jurek224466** [comment]
After the setup is done, everything works. I still have a question. Is it normal for the purple LED is on while the VPN is connected?
