### ISSUE TITLE
Feature/Package Request: mwan3

### ISSUE THREAD

**Issue by ahduyck** [SVoxel/ORBI-LBR20#3]
I was wondering if it would be possible to get the mwan3 package (https://openwrt.org/docs/guide-user/network/wan/multiwan/mwan3) installed in a future release so that the LBR20 could be configured as a load balancing router?

I would be good with it just being installed and not configured/enabled as I would be willing to work on setting up the configs myself if needed.

**Comment by SVoxel** [comment]
I am not sure that it would work as is if I just add it into firmware. The stock GPL odes are not the same as OpenWRT architecture... And I am not sure that it does not require some additional packages e.g. kernel modules.

Well, compiled 'as is', the only: I changed '/usr/libexec' directory to '/usr/bin'. You may install and play with this yourself using Overlay partition on Circle partition (see my QuickStart.txt). Resulting:

https://www.voxel-firmware.com/Downloads/mwan3_2.10.13.tar.gz

Voxel.

**Comment by ahduyck** [comment]
Thanks, I will try to take a look at it this week and get back to you with what I find.

**Comment by ahduyck** [comment]
Yeah, I think I see what you are talking about. The configuration scripts are a tangled mess with requesting just a dhcp address on an interface kicking off a set of scripts and new iptables rules.

I'll be working on this for a while. I will probably have to look at seeing if I can disable most of their policy code so I can squeeze the 'balanced' option in something akin to the 'failover' for wlan_policy without the ugliness of a script just sitting in a while[1] loop and just toggling wlan_type.
